# -*- coding: utf-8 -*-
"""LAB3_SelectData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MhPWymwZUrvNRSEnn0DiNHy4OHRJJgkY
"""

!pip install fiftyone

from google.colab import drive
drive.mount('/content/drive')
import os
os.chdir('/content/drive/My Drive/Colab Notebooks')

"""
https://docs.voxel51.com/index.html
Choose classes and create datasets"""

# !!!!! Do not execute this cell, till your choice of classes is not recorded in the spreadsheet!!!!!
# !!!!! UPDATE classes below with your own classes!!!!!
cl1 = "Bird"
cl2 = "Footwear"
cl3 = "Dog"

import fiftyone.zoo as foz
import fiftyone as fo

#dataset.delete()
dataset = foz.load_zoo_dataset(
    "open-images-v7",
    split="train",
    label_types=["detections"],  # Load detection labels
    # UPDATE
    classes = [cl1, cl2, cl3],
    max_samples= 800,
)

# change the directory below
data_dir = "/content/drive/My Drive/ML_IPData1"
! mkdir $data_dir
patches =  dataset.to_patches("ground_truth")
from fiftyone import ViewField as F

ds = patches.match(
    F("ground_truth.label").is_in(
        # UPDATE
        [cl1, cl2, cl3]
    )
)

# Export the object patches as an image classification directory tree
ds.export(
   export_dir=data_dir,
   dataset_type=fo.types.ImageClassificationDirectoryTree,
   label_field="ground_truth",
)

ds.first()

ds.first().ground_truth

import fiftyone as fo
session = fo.launch_app(ds)

drive.flush_and_unmount()

ds

patches